DROP SEQUENCE IF EXISTS part_numbers_seq;
CREATE SEQUENCE part_numbers_seq START WITH 50000;
DROP LANGUAGE IF EXISTS plpgsql;
CREATE LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION func_name()
RETURNS "trigger" AS 
$BODY$ 
BEGIN
INSERT INTO part_number VALUES nextval('part_numbers_seq');
END;
$BODY$
LANGUAGE plpgsql VOLATILE;

CREATE TRIGGER pop_part_num AFTER INSERT
ON part_nyc FOR EACH ROW 
EXECUTE PROCEDURE func_name()
